# Generated by Django 5.0.3 on 2026-08-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('detailed_answers', models.JSONField(default=dict, help_text='User answers mapping question_id -> user_answer')),
                ('evaluation_feedback', models.JSONField(default=dict, help_text='AI evaluation per question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('OPEN', 'Open Ended')], max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for MCQ')),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField()),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.chunk')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('documents', models.ManyToManyField(related_name='quizzes', to='documents.document')),
            ],
        ),
    ]
