# Generated by Django 5.0.3 on 2026-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='source_chunk_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of chunk IDs used to generate this question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('ADAPTIVE', 'Adaptive')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='scope',
            field=models.CharField(choices=[('FULL', 'Entire Document'), ('CHAPTER', 'Chapter'), ('COMPLEX', 'Complex Concepts')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='result',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of options for MCQ/TF'),
        ),
    ]
