# Generated by Django 5.0.3 on 2026-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='documents',
            field=models.ManyToManyField(related_name='chats', to='documents.document'),
        ),
    ]
